{"question_id": 111911, "image": "00675497_0.png", "text": "Generate the CADQuery code needed to create the CAD for the provided image. Just the code, no other words.", "category": "default", "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.296875, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(0.671875, 0.0).lineTo(0.671875, 0.24753289473684212).lineTo(0.0, 0.24753289473684212).lineTo(0.0, 0.0).close()\nsolid0=wp_sketch0.add(loop0).extrude(0.03125)\nsolid=solid0\n"}
{"question_id": 71404, "image": "00442545_0.png", "text": "Generate the CADQuery code needed to create the CAD for the provided image. Just the code, no other words.", "category": "default", "ground_truth": "import cadquery as cq\n# Generating a workplane for sketch 0\nwp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.5234375, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop0=wp_sketch0.moveTo(1.0421052631578949, 0.0).lineTo(1.0421052631578949, 1.5).lineTo(0.0, 1.5).lineTo(0.0, 0.0).close()\nloop1=wp_sketch0.moveTo(0.5210526315789474, 0.1736842105263158).circle(0.04736842105263158)\nloop2=wp_sketch0.moveTo(0.5210526315789474, 1.3263157894736843).circle(0.04736842105263158)\nsolid0=wp_sketch0.add(loop0).add(loop1).add(loop2).extrude(0.546875)\nsolid=solid0\n# Generating a workplane for sketch 1\nwp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.1484375, 0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop3=wp_sketch1.moveTo(0.0, -0.15394736842105264).threePointArc((0.15074013157894736, -0.3046875), (0.3014802631578947, -0.15394736842105264)).lineTo(0.3014802631578947, 0.0).lineTo(0.15074013157894736, 0.0).lineTo(0.0, 0.0).close()\nsolid1=wp_sketch1.add(loop3).extrude(0.4765625)\nsolid=solid.cut(solid1)\n# Generating a workplane for sketch 2\nwp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(-0.1484375, -0.75, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\nloop4=wp_sketch2.moveTo(0.15074013157894736, 0.0).lineTo(0.3014802631578947, 0.0).lineTo(0.3014802631578947, 0.15394736842105264).threePointArc((0.15074013157894736, 0.3046875), (0.0, 0.15394736842105264)).lineTo(0.0, 0.0).close()\nsolid2=wp_sketch2.add(loop4).extrude(0.4765625)\nsolid=solid.cut(solid2)\n"}
